server:
  port: 8761
# ·şÎñÃû³Æ
spring:
  application:
    name: zerer-eureka
eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/
